-- GENERATED by C->Haskell Compiler, version 0.16.3 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "System/LibVirt/Internal.chs" #-}{-# LANGUAGE ForeignFunctionInterface, StandaloneDeriving, DeriveDataTypeable #-}


{-# LINE 3 "System/LibVirt/Internal.chs" #-}


-- | Internal types definitions and low-level functions.
-- This module is not supposed to be imported by client code.
module System.LibVirt.Internal
  (Connection (..), Domain (..), Network (..)
  ) where

import Data.Generics
import Foreign
import Foreign.C.Types
import Foreign.C.String

newtype Connection = Connection (Ptr (Connection))
{-# LINE 18 "System/LibVirt/Internal.chs" #-}

deriving instance Eq Connection
deriving instance Data Connection
deriving instance Typeable Connection

instance Show Connection where
  show (Connection ptr) = "<Connection: " ++ show ptr ++ ">"

newtype Domain = Domain (Ptr (Domain))
{-# LINE 27 "System/LibVirt/Internal.chs" #-}

deriving instance Eq Domain
deriving instance Data Domain
deriving instance Typeable Domain

instance Show Domain where
  show (Domain ptr) = "<Domain: " ++ show ptr ++ ">"

newtype Network = Network (Ptr (Network))
{-# LINE 36 "System/LibVirt/Internal.chs" #-}

deriving instance Eq Network
deriving instance Data Network
deriving instance Typeable Network

instance Show Network where
  show (Network ptr) = "<Network: " ++ show ptr ++ ">"

